### ISSUE TITLE
Application crashing when using AnyLine SDK 25

### ISSUE THREAD

**Issue by sandeepmnit** [Anyline/anyline-ocr-examples-android#10]
**Defined the scanView in XML** 
    <io.anyline.view.ScanView
        android:id="@+id/scan_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

**getting below crash when opening my activity.**

2020-11-05 15:19:56.694 8796-8796/com.vyntelligence.vyn E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.test, PID: 8796
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.test/com.example.test.views.activities.ScanBarcodeActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class io.anyline.view.ScanView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class io.anyline.view.ScanView
     Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class io.anyline.view.ScanView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:695)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:174)
        at com.vyntelligence.vyn.views.activities.ScanBarcodeActivity.onCreate(ScanBarcodeActivity.java:33)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/util/concurrent/MoreExecutors;
        at io.anyline.view.ScanView.<init>(SourceFile:20)
        at io.anyline.view.ScanView.<init>(SourceFile:2)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:695) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:174) 
        at com.vyntelligence.vyn.views.activities.ScanBarcodeActivity.onCreate(ScanBarcodeActivity.java:33) 
        at android.app.Activity.performCreate(Activity.java:6975) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.util.concurrent.MoreExecutors" on path: DexPathList[[zip file "/data/app/com.example.test-rOXuiikEOmNccnM1_pUO5g==/base.apk"],nativeLibraryDirectories=[/data/app/com.vyntelligence.vyn-rOXuiikEOmNccnM1_pUO5g==/lib/x86, /data/app/com.vyntelligence.vyn-rOXuiikEOmNccnM1_pUO5g==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.anyline.view.ScanView.<init>(SourceFile:20) 
        at io.anyline.view.ScanView.<init>(SourceFile:2) 
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:695) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:174) 
        at com.example.test.activities.ScanBarcodeActivity.onCreate(ScanBarcodeActivity.java:33) 
        at android.app.Activity.performCreate(Activity.java:6975) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 

**Activity code** 
`import android.os.Bundle;
import android.util.Log;
import android.view.WindowManager;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

import at.nineyards.anyline.camera.CameraController;
import at.nineyards.anyline.camera.CameraOpenListener;
import io.anyline.plugin.ScanResultListener;
import io.anyline.plugin.barcode.BarcodeScanResult;
import io.anyline.plugin.barcode.BarcodeScanViewPlugin;
import io.anyline.view.BaseScanViewConfig;
import io.anyline.view.ScanView;
import io.anyline.view.ScanViewPluginConfig;

/**
 * Example activity for the Anyline-Barcode-Module
 */
public class ScanBarcodeActivity extends AppCompatActivity implements CameraOpenListener {

    private static final String TAG = ScanBarcodeActivity.class.getSimpleName();
    private ScanView barcodeScanView;
    private TextView resultText;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_any_line_scan);
        //Set the flag to keep the screen on (otherwise the screen may go dark during scanning)
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);

        //resultText = (TextView) findViewById(R.id.text_result);

        barcodeScanView = (ScanView) findViewById(R.id.scan_view);
        // add a camera open listener that will be called when the camera is opened or an error occurred
        //  this is optional (if not set a RuntimeException will be thrown if an error occurs)
        barcodeScanView.setCameraOpenListener(this);
        // the view can be configured via a json file in the assets, and this config is set here
        // (alternatively it can be configured via xml, see the Energy Example for that)
        //barcodeScanView.setScanConfig("barcode_view_config.json");

        // optionally limit the barcode format to (multiple) specific types
        //barcodeScanView.setBarcodeFormats(BarcodeScanView.BarcodeFormat.QR_CODE,
        //        BarcodeScanView.BarcodeFormat.CODE_128);
        //init the scanViewPlugin configuration which hold the scan view ui configuration (cutoutConfig and ScanFeedbackConfig)
        ScanViewPluginConfig barcodeScanviewPluginConfig = new ScanViewPluginConfig(getApplicationContext(), "barcode_view_config.json");
        //init the scan view
        BarcodeScanViewPlugin scanViewPlugin = new BarcodeScanViewPlugin(getApplicationContext(), getString(R.string.anyline_license_key), barcodeScanviewPluginConfig, "BARCODE");
        //init the base scanViewconfig which hold camera and flash configuration
        BaseScanViewConfig barcodeBaseScanViewConfig = new BaseScanViewConfig(getApplicationContext(), "barcode_view_config.json");
        //set the base scanViewConfig to the ScanView
        barcodeScanView.setScanViewConfig(barcodeBaseScanViewConfig);
        //set the scanViewPlugin to the ScanView
        barcodeScanView.setScanViewPlugin(scanViewPlugin);
        //add result listener
        scanViewPlugin.addScanResultListener(new ScanResultListener<BarcodeScanResult>() {
            @Override
            public void onResult(BarcodeScanResult result) {
                //resultText.setText(result.getResult().get(0).getValue());
            }
        });
    }

    @Override
    protected void onResume() {
        super.onResume();
        //start the actual scanning
        barcodeScanView.start();
    }

    @Override
    protected void onPause() {
        super.onPause();
        //stop the scanning
        barcodeScanView.stop();
        //release the camera (must be called in onPause, because there are situations where
        // it cannot be auto-detected that the camera should be released)
        barcodeScanView.releaseCameraInBackground();
    }

    @Override
    public void onCameraOpened(CameraController cameraController, int width, int height) {
        //the camera is opened async and this is called when the opening is finished
        Log.d(TAG, "Camera opened successfully. Frame resolution " + width + " x " + height);
    }

    @Override
    public void onCameraError(Exception e) {
        //This is called if the camera could not be opened.
        // (e.g. If there is no camera or the permission is denied)
        // This is useful to present an alternative way to enter the required data if no camera exists.
        throw new RuntimeException(e);
    }
}`

**Comment by lore-any** [comment]
Hi @sandeepmnit , here is Lorena from Anyline. Could you please let as know how do you load Anyline25 in your build gradle? 
Thank you!

**Comment by sandeepmnit** [comment]
Hi @lore-any I am loading like below code
**implementation 'io.anyline:anylinesdk:20@aar'**

**Comment by lore-any** [comment]
Hi @sandeepmnit . Thank you for your answer. Could you please try:  implementation'io.anyline:anylinesdk:25' 
Thank you!

**Comment by sandeepmnit** [comment]
@lore-any Getting below crash while using implementation'io.anyline:anylinesdk:25'

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.vyntelligence.vyn-sJ2mKBPdj9E8FtrToStOSA==/base.apk"],nativeLibraryDirectories=[/data/app/com.vyntelligence.vyn-sJ2mKBPdj9E8FtrToStOSA==/lib/x86, /data/app/com.vyntelligence.vyn-sJ2mKBPdj9E8FtrToStOSA==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libopencv_java3_al.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at io.anyline.plugin.AbstractScanPlugin.<clinit>(SourceFile:1)
        at com.vyntelligence.vyn.views.activities.AnyLineScanActivity.setupBarcodeReadingPlugin(AnyLineScanActivity.kt:49)
        at com.vyntelligence.vyn.views.activities.AnyLineScanActivity.onCreate(AnyLineScanActivity.kt:40)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by lore-any** [comment]
Dear sandeepmnit, please be aware that starting Anyline version 25, we do not support anymore x86 arch. 

Best,
Lorena K.

**Comment by lore-any** [comment]
Hi @sandeepmnit . As there were no additional comments from your side in the last 12 days, we consider this issue closed. If you have any other issue, please open a new one and we are more than happy to help.
