### ISSUE TITLE
NoSuchMethodError: No virtual method getDisplay() in class Context

### ISSUE THREAD

**Issue by davidmigloz** [Anyline/anyline-ocr-examples-android#17]
Hi team,

I'm seeing the following crash in version 30.1 of the AnyLine sdk:

```
Fatal Exception: android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class io.anyline.view.ScanView
       at android.view.LayoutInflater.inflate(LayoutInflater.java:558)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:434)
       at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
       at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1368)
       at com.xxx.XXXBinding.inflate(XXXBinding.java:53)
       at com.xxx.XXXBinding.inflate(XXXBinding.java:39)
       at com.xxx.XXXFragment.onCreateView(XXXFragment.java:68)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2950)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:515)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5621)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
Caused by java.lang.NoSuchMethodError: No virtual method getDisplay()Landroid/view/Display; in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar)
       at at.nineyards.anyline.camera.CameraUtil.getDisplayRotationDegrees(CameraUtil.java:1)
       at at.nineyards.anyline.camera.CameraUtil.getCameraDisplayRotation(CameraUtil.java:4)
       at at.nineyards.anyline.camera.CameraController1.<init>(CameraController1.java:123)
       at at.nineyards.anyline.camera.CameraView.a(CameraView.java:6)
       at at.nineyards.anyline.camera.CameraView.<init>(CameraView.java:154)
       at io.anyline.view.ScanView.<init>(ScanView.java:3)
       at io.anyline.view.ScanView.<init>(ScanView.java:2)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at android.view.LayoutInflater.createView(LayoutInflater.java:638)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:783)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:723)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:817)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:434)
       at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
       at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1368)
       at com.xxx.inflate(XXXBinding.java:53)
       at com.xxx.XXXBinding.inflate(XXXBinding.java:39)
       at com.xxx.XXXFragment.onCreateView(XXXFragment.java:68)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2950)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:515)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5621)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
```

The affected customers were using Android 6.

Checking the Android docs, [`Context.getDisplay()`](https://developer.android.com/reference/android/content/Context#getDisplay()) was added in API 30, so that may be the reason?

Thanks.

**Comment by davidmigloz** [comment]
Sorry, actually these customers were using a version of our app that used AnyLine v28.1. I don't see any affected customer using our newest version that ships AnyLine v30.1. So probably you already addressed this issue. I'll close the ticket and reopen it if I still see it in the newest SDK.
