### ISSUE TITLE
NullPointerException after start ScanView with universal id configuration on Pixel 4a with Android 11 

### ISSUE THREAD

**Issue by petermiklanek** [Anyline/anyline-ocr-examples-android#20]
Exception:
```
java.lang.NullPointerException
        at android.content.res.XmlBlock.nativeGetStyleAttribute(Native Method)
        at android.content.res.XmlBlock.access$1500(XmlBlock.java:41)
        at android.content.res.XmlBlock$Parser.getStyleAttribute(XmlBlock.java:459)
        at android.content.res.Resources$Theme.getExplicitStyle(Resources.java:1827)
        at android.view.View.retrieveExplicitStyle(View.java:6348)
        at android.view.View.<init>(View.java:5474)
        at android.view.View.<init>(View.java:5430)
        at android.view.View.<init>(View.java:5409)
        at io.anyline.view.AnylineFeedbackView.<init>(SourceFile:1)
        at io.anyline.view.ScanView.b(SourceFile:29)
        at io.anyline.view.ScanView.$r8$lambda$XMQ9vxgMy9VgYJHKOZXNfRghkI0(Unknown Source:0)
        at io.anyline.view.ScanView$$ExternalSyntheticLambda14.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Implementation:
```
binding.scanView.init(UNIVERSAL_ID_CONFIG)
val scanViewPlugin = binding.scanView.scanViewPlugin as? IdScanViewPlugin
scanViewPlugin?.addScanResultListener(ScanResultListener { idScanResult: ScanResult<ID<*>?> ->
	...
} as ScanResultListener<ScanResult<ID<*>?>>)
```

Config:
```
{
  "camera": {
    "captureResolution": "1080p",
    "zoomGesture": true
  },
  "flash": {
    "mode": "none"
  },
  "viewPlugin": {
    "plugin": {
      "id": "ID",
      "idPlugin": {
        "universalIdConfig": {
          "faceDetection": true,
          "allowedLayouts": {}
        }
      }
    },
    "cutoutConfig": {
      "style": "animated_rect",
      "maxWidthPercent": "90%",
      "maxHeightPercent": "90%",
      "alignment": "center",
      "strokeWidth": 8,
      "cornerRadius": 8,
      "strokeColor": "FFFFFF",
      "outerColor": "000000",
      "outerAlpha": 0.3,
      "ratioFromSize": {
        "width": 50,
        "height": 31
      },
      "cropPadding": {
        "x": -50,
        "y": -50
      },
      "cropOffset": {
        "x": 0,
        "y": 0
      },
      "feedbackStrokeColor": "0099FF"
    },
    "scanFeedback": {
      "style": "CONTOUR_RECT",
      "visualFeedbackRedrawTimeout": 100,
      "strokeColor": "0099FF",
      "fillColor": "220099FF",
      "beepOnResult": true,
      "vibrateOnResult": true,
      "strokeWidth": 2
    },
    "cancelOnResult": true
  }
}
```

**Comment by nosko** [comment]
Hello guys,
any update on this please?

I'm running almost the same configuration like @petermiklanek with the same crash

`private fun setupScannerView() {
        binding.scanView.apply {
            init("anyline_config.json")

            scanViewPlugin.apply {
                addScanRunSkippedListener {}
                addScanResultListener {}
            }
        }
    }`

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
