### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found

### ISSUE THREAD

**Issue by vsanpr** [Anyline/anyline-ocr-examples-android#42]
Hello
Users while using my application keep getting this exception and as a result the application crash
The way to reproduce this issue is:
open scanner screen
minimize application
do some actions (in my case is to open camera, make some photos, open gallery)
resume application
crash happens
While opening the scanner regularly there are no issues with it.
Here is the exception
`No implementation found for void at.nineyards.anyline.core.asset_serviceJNI.swig_module_init() (tried Java_at_nineyards_anyline_core_asset_1serviceJNI_swig_1module_1init and Java_at_nineyards_anyline_core_asset_1serviceJNI_swig_1module_1init__)`

`E  FATAL EXCEPTION: main
                                                                                                    Process: com.app.test, PID: 5939
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for void at.nineyards.anyline.core.asset_serviceJNI.swig_module_init() (tried Java_at_nineyards_anyline_core_asset_1serviceJNI_swig_1module_1init and Java_at_nineyards_anyline_core_asset_1serviceJNI_swig_1module_1init__)
                                                                                                    	at at.nineyards.anyline.core.asset_serviceJNI.swig_module_init(Native Method)
                                                                                                    	at at.nineyards.anyline.core.asset_serviceJNI.<clinit>(SourceFile:1)
                                                                                                    	at at.nineyards.anyline.core.AssetDelegate.<init>(SourceFile:4)
                                                                                                    	at io.anyline.trainer.AssetController.<init>(SourceFile:1)
                                                                                                    	at io.anyline.plugin.AbstractScanPlugin.<init>(SourceFile:44)
                                                                                                    	at io.anyline.plugin.barcode.BarcodeScanPlugin.<init>(SourceFile:1)
                                                                                                    	at com.app.test.ScanBarcodeActivity.initScanPlugin(ScanBarcodeActivity.java:138)
                                                                                                    	at com.app.test.ScanBarcodeActivity.onCreate(ScanBarcodeActivity.java:115)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7963)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7952)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:237)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8167)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
