### ISSUE TITLE
[Android] - Crash when scanning QR code with Anyline@21

### ISSUE THREAD

**Issue by marcherdiego** [Anyline/anyline-ocr-examples-android#8]
This is not 100% reproducible, it happened at least four times in this device:

**Device**
> Brand: samsung
> Model: Galaxy S8
> Orientation: Portrait
> RAM free: 1.04 GB
> Disk free: 38.92 GB

**Operating System**
> Version: 9
> Orientation: Portrait
> Rooted: No

**We are using Anyline version 21**

```kotlin
Fatal Exception: java.lang.IllegalStateException: No yuv image set!
       at at.nineyards.anyline.camera.ImageReceiver.getYuvImage(SourceFile:81)
       at io.anyline.plugin.AbstractScanPlugin.getLastImageWithFullSize(SourceFile:245)
       at io.anyline.plugin.barcode.BarcodeScanPlugin.f(SourceFile:34)
       at io.anyline.plugin.barcode.BarcodeScanPlugin$1.onSuccess(SourceFile:133)
       at at.nineyards.anyline.camera.NativeBarcodeDetectionThread$1$2.onSuccess(SourceFile:1141)
       at com.google.android.gms.tasks.zzn.run(:4)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Comment by melaniamuir** [comment]
Hello, thanks for reporting this issue. 
We tested QR code scanning with our current Android demo app and were able to scan all QR codes successfully. 
Could you please try downloading the demo app from Google PlayStore on the same device and let us know if the QR code is successfully scanned with our app?

**Comment by marcherdiego** [comment]
We tried that and what happened was that the screen behaved a little bit strange but then scanned the QR code.

This is happening when using `parallelViewPluginComposite`.
These are the configuration file and kotlin code we are using to set it up:

**composite_view_config.json**
```json
{
  "camera": {
    "captureResolution": "1080p",
    "pictureResolution": "1080p"
  },
  "parallelViewPluginComposite": {
    "id": "LP_DL_VIN",
    "cancelOnResult": false,
    "viewPlugins": [
      {
        "viewPlugin": {
          "plugin": {
            "id": "BARCODE",
            "barcodePlugin": {
            }
          },
          "cutoutConfig": {
            "style": "rect",
            "maxWidthPercent": "80%",
            "maxHeightPercent": "80%",
            "alignment": "center",
            "width": 900,
            "ratioFromSize": {
              "width": 1,
              "height": 1
            },
            "strokeWidth": 2,
            "cornerRadius": 10,
            "strokeColor": "FFFFFF",
            "outerColor": "000000",
            "outerAlpha": 0.3,
            "feedbackStrokeColor": "0099FF"
          },
          "scanFeedback": {
            "animationDuration": 250,
            "style": "contour_point",
            "strokeWidth": 2,
            "strokeColor": "0099FF",
            "fillColor": "220099FF",
            "beepOnResult": true,
            "vibrateOnResult": false,
            "blinkAnimationOnResult": true
          },
          "cancelOnResult": false
        }
      },
      {
        "viewPlugin": {
          "plugin": {
            "id": "VIN",
            "ocrPlugin": {
              "scanMode": "AUTO"
            }
          },
          "cutoutConfig": {
            "style": "rect",
            "maxWidthPercent": "80%",
            "alignment": "center",
            "width": 900,
            "ratioFromSize": {
              "width": 62,
              "height": 9
            },
            "outerColor": "000000",
            "outerAlpha": 0.3,
            "strokeWidth": 2,
            "strokeColor": "FFFFFF",
            "cornerRadius": 4,
            "feedbackStrokeColor": "0099FF"
          },
          "scanFeedback": {
            "animation": "traverse_multi",
            "animationDuration": 250,
            "style": "contour_rect",
            "strokeWidth": 2,
            "strokeColor": "0099FF",
            "fillColor": "220099FF",
            "beepOnResult": true,
            "vibrateOnResult": false,
            "blinkAnimationOnResult": true
          },
          "cancelOnResult": false
        }
      }
    ]
  }
}
```

**ScannerActivity.kt**
```kotlin
private val scanView: ScanView = activity.findViewById(R.id.scan_view)

fun setScanConfig(scannerConfig: String, anylineLicenseKey: String) {
    scanView.init(scannerConfig, anylineLicenseKey)
    scanView.scanViewPlugin.allScanViewPlugins.forEach {
        it.addScanResultListener { result ->
            val scanResult = result.result.toString()
            ...
        }
    }
}
```

**Comment by gseebacher** [comment]
Hi Diego,

please set the parameter "cancelOnResult" to true (for all 3 occurrences of this parameter)

furthermore - just for a better user experience - avoid overlapping cutouts. e.g. place one cutout at the top 
"alignment": "top"
and add an offset, e.g.
"offset": {
              "x": 0,
              "y": 120
            }

hope this helps.
cheers,
Gerhard

**Comment by marcherdiego** [comment]
Hi,

We are not cancelling the scan because of some false-positives the library prompted as result while using the OCR feature for VINs.

If we use `cancelOnResult = true` will we be able to scan again without needing to setup the `scanView` again with the `json` configuration file?
