### ISSUE TITLE
Application crash when using Anyline SDK 20 for barcode scanning.

### ISSUE THREAD

**Issue by sandeepmnit** [Anyline/anyline-ocr-examples-android#9]
I am getting crash when trying to scan the barcode using anylineSDK 20.

2020-11-05 15:15:26.826 8352-8352/com.vyntelligence.vyn E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.test, PID: 8352
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/ml/vision/barcode/FirebaseVisionBarcodeDetectorOptions$Builder;
        at at.nineyards.anyline.camera.NativeBarcodeDetectionThread.<init>(SourceFile:41)
        at at.nineyards.anyline.camera.NativeBarcodeDetector.enableBarcodeDetection(SourceFile:46)
        at at.nineyards.anyline.camera.CameraView.enableBarcodeDetection(SourceFile:693)
        at io.anyline.plugin.barcode.BarcodeScanPlugin.start(SourceFile:117)
        at io.anyline.view.AbstractScanViewPlugin.start(SourceFile:122)
        at io.anyline.view.ScanView.a(SourceFile:324)
        at io.anyline.view.ScanView.start(SourceFile:359)
        at com.vyntelligence.vyn.views.activities.ScanBarcodeActivity.onResume(ScanBarcodeActivity.java:73)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
        at android.app.Activity.performResume(Activity.java:7079)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2898)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.ml.vision.barcode.FirebaseVisionBarcodeDetectorOptions$Builder" on path: DexPathList[[zip file "/data/app/com.vyntelligence.vyn-GUfFHkz-I2cmJGQVKUwJnw==/base.apk"],nativeLibraryDirectories=[/data/app/com.vyntelligence.vyn-GUfFHkz-I2cmJGQVKUwJnw==/lib/x86, /data/app/com.vyntelligence.vyn-GUfFHkz-I2cmJGQVKUwJnw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at at.nineyards.anyline.camera.NativeBarcodeDetectionThread.<init>(SourceFile:41) 
        at at.nineyards.anyline.camera.NativeBarcodeDetector.enableBarcodeDetection(SourceFile:46) 
        at at.nineyards.anyline.camera.CameraView.enableBarcodeDetection(SourceFile:693) 
        at io.anyline.plugin.barcode.BarcodeScanPlugin.start(SourceFile:117) 
        at io.anyline.view.AbstractScanViewPlugin.start(SourceFile:122) 
        at io.anyline.view.ScanView.a(SourceFile:324) 
        at io.anyline.view.ScanView.start(SourceFile:359) 
        at com.vyntelligence.vyn.views.activities.ScanBarcodeActivity.onResume(ScanBarcodeActivity.java:73) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354) 
        at android.app.Activity.performResume(Activity.java:7079) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2898) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by lore-any** [comment]
Dear @sandeepmnit , did you try our latest android SDK version - 26.1?
Please let us know if you still face the issue.

**Comment by sandeepmnit** [comment]
@lore-any Thanks for your support. This issue has been resolved but facing couple of issue while doing the scanning. I will raise those issues with video with you soon for your support. I didn't try SDK 26.1 right now but that is in my plan.
